### PR TITLE
Add items  to Main Menu

### PR DESCRIPTION
**Pull request by andreasnyh**
A start to the menu!

Co-authored-by: Simon Nordström <nordstromas@gmail.com>

### CODE REVIEW

**Comment by SimonNord** [comment]
Skärmavbild 2020-06-18 kl  11 41 58

**Comment by SimonNord** [comment]
Skärmavbild 2020-06-18 kl  14 09 32

**Comment by SimonNord** [comment]
is this ok to merge? :O

**Comment by andreasnyh** [comment]
> is this ok to merge? :O

I believe it is!

**Pull request merged**
